export const LOAD_INVESTMENT_DATA = 'LOAD_INVESTMENT_DATA';
export const LOAD_INVESTMENT_DATA_LOADING = 'LOAD_INVESTMENT_DATA_LOADING';
export const LOAD_INVESTMENT_DATA_SUCCESS = 'LOAD_INVESTMENT_DATA_SUCCESS';
export const LOAD_INVESTMENT_DATA_FAILED = 'LOAD_INVESTMENT_DATA_FAILED';